### ISSUE TITLE
Document indexes and default queries

### ISSUE THREAD

**Issue by hscasn** [gmrutilus/gmrutilus.github.io#21]
**Default queries:**

located in presets/defaultQueries.js

It will look in the database and check if there are presets without queries. if there are, it will insert the queries for that preset.

**Indexes**

Located in /schema/misc/defaultIndexes.js

You only change this file if you want to CHANGE the default indexes. if you want to add more, you can pass an extra configuration:

```
extraIndexes: {

        // Users
        users: [
            "field1",
            "field2",
        ],

    }
```

This will index field1 and field2 in the "users" collection.

These are the collections available:

accounts, browsers, browsers, cpus, devices, engines, hits, operatingSystems, queries, resources, sessions, uatCache, users.

If you try to make a new index and it is illegal, or not supported by the schema, you will get an error. Do not use dots to try to index sub elements.

There is another pseudo-collection available: actions, so you can index elements of the actions sub-element in the hit.

**Comment by welkie** [comment]
Finished.

Commit: https://github.com/gmrutilus/gmrutilus.github.io/commit/8df4f05a5c9b6beaa69cc30032e42b96fdecaae3
