### ISSUE TITLE
List of hooks

### ISSUE THREAD

**Issue by hscasn** [gmrutilus/gmrutilus.github.io#26]
css
class
rutilus-body-image
rutilus-body-video
comment-count
rutilus-title-3
rutilus-title-2
rutilus-title-1
rutilus-body
rutilus-ad

id
rutilus-source-type
rutilus-source-id
rutilus-tags
rutilus-footer

input
rutilus-user-id
rutilus-user-display-name

ad iframe

**Comment by welkie** [comment]
All hooks covered in documentation. Need to review user info (where is it stored?) and tags (how important are they? are they mandatory?).

Commit: https://github.com/gmrutilus/gmrutilus.github.io/commit/9fff15ec6a1f41bb08a192cff9509033ca0d54cf

**Comment by welkie** [comment]
Finished.

Commit: https://github.com/gmrutilus/gmrutilus.github.io/commit/6645f23e8c7f23fc522c61b22ffe9b5e436db57d
